package Assignment;

public enum TableStatus {
    INACTIVE,
    CONFIRMED_BY_COUNTRY,
    HIGHEST_LOWEST_DEATH_RECOVERED_BY_COUNTRY,
    CONFIRMED_DEATHS_RECOVERED_CASES_BY_COUNTRY,
    SORTED_ASC_CONFIRMED_BY_COUNTRY,
    SORTED_DSC_CONFIRMED_BY_COUNTRY
}
